---
#  K3 File Prep play
#	1. Split source file into segments
#	2. Copies each group of files to target machines
#	3. Clean up source segements in source folder
#
#	NOTE: File names are re-numberred on target machines. Each set is ordered 0..numProcs

- hosts:  source_hosts

  tasks:
  - name: Split source file into partitions
    command: chdir={{source|dirname}} split -n l/{{ numProcs*groups['target_hosts']|length }} --numeric-suffixes -a 3 {{source|basename }} {{source|basename }}


- hosts: target_hosts

  sudo: True

  tasks:
  - name: Create data dir, if needed
    file: dest={{destination}} state=directory mode=775 group=damsl

  - name: Copy files to destination machines
    copy: src={{source}}{{ "%03d" | format((item|int) + ((peer|int) * (numProcs|int)))}} dest={{destination}}/{{source|basename }}{{ "%03d" | format(item|int)}}
    with_sequence: start=0 end={{numProcs-1}}


- hosts: source_hosts

  tasks:
  - name: Clean up source file segments
    command: rm -f {{source}}{{item}}
    with_sequence: start=0 end={{((numProcs)*groups['target_hosts']|length)-1}} format=%03d
